let language="ja";
const strings={
ja:{concept:"楽器も声も、「音」として測る。",handsTitle:"STARTしたら、あとは音を鳴らすだけ。",handsText:"楽器の演奏や発声を自動解析。スマートフォンを置いたまま、START後はハンズフリーで使用できます。",start:"START ANALYSIS",privacy:"音声はブラウザ内で解析され、サーバーへ送信されません。",testNote:"Phase 1ではマイク入力・RMS・Peak・Input Qualityのみ実測です。Pitch / Spectrum / Harmonics / Vocal値はテスト表示です。",howTitle:"START後はハンズフリー。",step1:"スマートフォンを置く",step3:"楽器を鳴らす / 歌う",step4:"自動解析",step5:"結果を見る",phase1About:"LOW INPUT / GOOD / CLIP はマイク入力品質の状態です。Pitchの正しさを示すものではありません。",lowAbout:"入力が小さく、Pitch解析に適さない可能性があります。",goodAbout:"入力レベルが解析に適した範囲です。",clipAbout:"入力が大きすぎます。端末を音源から少し離してください。",thresholdNote:"LOW INPUT閾値とCLIP表示保持時間はPhase 1実機評価用の初期値です。端末比較後に調整します。",privacyLong:"音声の録音・保存は行いません。解析に必要な音声データと解析結果はブラウザ内で一時的に処理されます。",toneNote:"Phase 1ではReference ToneはUIのみです。音はPhase 3で実装します。"},
en:{concept:'Measure instruments and vocals simply as "sound."',handsTitle:"Start once, then just play or sing.",handsText:"Your instrument or voice is analyzed automatically. Place your device nearby and use it hands-free after START.",start:"START ANALYSIS",privacy:"Audio is analyzed locally in your browser and is not sent to a server.",testNote:"In Phase 1, only microphone input, RMS, Peak and Input Quality are live measurements. Pitch, Spectrum, Harmonics and Vocal values are test data.",howTitle:"Hands-free after START.",step1:"Place your device nearby",step3:"Play an instrument / Sing",step4:"Automatic analysis",step5:"View the result",phase1About:"LOW INPUT / GOOD / CLIP describe microphone input quality, not pitch correctness.",lowAbout:"The input may be too quiet for reliable pitch analysis.",goodAbout:"The input level is suitable for analysis.",clipAbout:"The input is too loud. Move the device slightly away from the sound source.",thresholdNote:"The LOW INPUT threshold and CLIP display hold time are initial Phase 1 calibration values and will be tuned after device testing.",privacyLong:"Audio is not recorded or saved. Audio samples and analysis results required for processing exist only temporarily in browser memory.",toneNote:"Reference Tone is UI-only in Phase 1. Audio playback begins in Phase 3."}};
const messages={
ja:{REQUESTING:"マイクの使用許可を確認しています…",READY:"MICROPHONE READY",LOW:"LOW INPUT",CLIP:"CLIP — 端末を音源から少し離してください",MICROPHONE_BLOCKED:"MICROPHONE BLOCKED — マイクの使用を許可してください",MICROPHONE_NOT_FOUND:"MICROPHONE NOT FOUND",MICROPHONE_UNAVAILABLE:"MICROPHONE UNAVAILABLE",SECURE_CONTEXT_REQUIRED:"SECURE CONTEXT REQUIRED — HTTPSで開いてください",AUDIO_INITIALIZATION_FAILED:"AUDIO INITIALIZATION FAILED",NOT_STARTED:"NOT STARTED"},
en:{REQUESTING:"Requesting microphone permission…",READY:"MICROPHONE READY",LOW:"LOW INPUT",CLIP:"CLIP — Move the device slightly away",MICROPHONE_BLOCKED:"MICROPHONE BLOCKED — Allow microphone access",MICROPHONE_NOT_FOUND:"MICROPHONE NOT FOUND",MICROPHONE_UNAVAILABLE:"MICROPHONE UNAVAILABLE",SECURE_CONTEXT_REQUIRED:"SECURE CONTEXT REQUIRED — Open over HTTPS",AUDIO_INITIALIZATION_FAILED:"AUDIO INITIALIZATION FAILED",NOT_STARTED:"NOT STARTED"}};
export function getLanguage(){return language}export function msg(k){return messages[language]?.[k]??k}
export function setLanguage(lang){language=lang;document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const v=strings[lang]?.[el.dataset.i18n];if(v!==undefined)el.textContent=v});document.querySelectorAll("[data-ja-only]").forEach(el=>el.hidden=lang!=="ja");document.getElementById("langJa")?.classList.toggle("is-active",lang==="ja");document.getElementById("langEn")?.classList.toggle("is-active",lang==="en");}
