let language="ja";
const strings={
ja:{
concept:"楽器も声も、「音」として測る。",handsTitle:"STARTしたら、あとは音を鳴らすだけ。",handsText:"楽器の演奏や発声を自動解析。スマートフォンを置いたまま、START後はハンズフリーで使用できます。",start:"START ANALYSIS",privacy:"音声はブラウザ内で解析され、サーバーへ送信されません。",
howTitle:"START後はハンズフリー。",step1:"スマートフォンを置く",step3:"楽器を鳴らす / 歌う",step4:"自動解析",step5:"結果を見る",
vocalHow:"VOCALでは、約1秒の無音で計測を停止し、結果を画面に保持します。1回の計測は最大30秒です。次の発声で新しい計測を自動開始します。",
whatTitle:"音を、数字と波形で観察。",whatTuner:"音名、周波数、基準周波数との差をcentで表示します。",whatSound:"波形、周波数スペクトル、H1–H8、Spectral Centroidを表示します。",whatVocal:"Pitch History、平均Pitch、計測範囲、Pitch Variation、Vibratoを観察できます。",
dataTitle:"データは一時的に処理。",dataText:"VOCALの時系列データは計測・表示のためブラウザ内で一時的に保持されます。音声そのものを録音・保存する機能ではありません。計測停止後は直前の結果を画面に保持し、次の計測開始時に更新します。",
measureTitle:"端末やマイクによって結果は変わります。",measureText:"本ツールの測定結果は、使用する端末・マイク・OS・ブラウザ・音声処理機能によって異なる場合があります。内蔵マイクや端末の音声処理は人の声を主な対象として設計されている場合があり、楽器音、低音・高音、持続音などが抑制されることがあります。",
measureDetail:"ノイズ抑制、エコーキャンセル、自動ゲイン調整、風切り音低減、空間オーディオなどが入力音へ影響する場合があります。本ツールはブラウザから可能な範囲で音声処理を抑制する設定を要求しますが、端末・OS・ドライバ等による処理を完全には制御できません。楽器音を検出しにくい場合は、音声設定やマイクとの距離を確認するか、楽器収音に適した外部マイクをお試しください。",
privacyLong:"音声の録音・保存は行いません。解析に必要な音声データと解析結果はブラウザ内で一時的に処理されます。",toneHelp:"基準音の再生中はマイク入力をいったん解放します。STOP TONE後にマイクを再取得し、自動的に計測へ復帰します。"},
en:{
concept:'Measure instruments and vocals simply as "sound."',handsTitle:"Start once, then just play or sing.",handsText:"Your instrument or voice is analyzed automatically. Place your device nearby and use it hands-free after START.",start:"START ANALYSIS",privacy:"Audio is analyzed locally in your browser and is not sent to a server.",
howTitle:"Hands-free after START.",step1:"Place your device nearby",step3:"Play an instrument / Sing",step4:"Automatic analysis",step5:"View the result",
vocalHow:"In VOCAL mode, measurement stops after about one second of silence and the result remains on screen. Each measurement lasts up to 30 seconds. The next vocal sound starts a new measurement automatically.",
whatTitle:"Observe sound as numbers and waveforms.",whatTuner:"Shows note, frequency, and the difference from the reference pitch in cents.",whatSound:"Shows waveform, frequency spectrum, H1–H8 harmonics, and Spectral Centroid.",whatVocal:"Observe Pitch History, average pitch, measured pitch range, Pitch Variation, and Vibrato.",
dataTitle:"Data is processed temporarily.",dataText:"VOCAL time-series data is held temporarily in browser memory for measurement and display. This is not audio recording or storage. After measurement stops, the latest result remains visible until the next measurement begins.",
measureTitle:"Results depend on your device and microphone.",measureText:"Measurement results may vary with the device, microphone, OS, browser, and audio-processing features. Built-in microphones and device processing may be optimized mainly for speech and can suppress instrument sounds, low or high frequencies, or sustained tones.",
measureDetail:"Noise suppression, echo cancellation, automatic gain control, wind-noise reduction, spatial audio, and similar processing may affect microphone input. This tool requests reduced processing where browsers allow it, but cannot fully control processing performed by the device, OS, or driver. If instrument sounds are difficult to detect, check audio settings and microphone distance, or try an external microphone suitable for instruments.",
privacyLong:"Audio is not recorded or saved. Audio samples and analysis results required for processing exist only temporarily in browser memory.",toneHelp:"While the reference tone is playing, microphone input is fully released. After STOP TONE, the microphone is reacquired and measurement resumes automatically."}};
const messages={
ja:{REQUESTING:"マイクの使用許可を確認しています…",READY:"MICROPHONE READY",LOW:"LOW INPUT",CLIP:"CLIP — 端末を音源から少し離してください",MICROPHONE_BLOCKED:"MICROPHONE BLOCKED — マイクの使用を許可してください",MICROPHONE_NOT_FOUND:"MICROPHONE NOT FOUND",MICROPHONE_UNAVAILABLE:"MICROPHONE UNAVAILABLE",SECURE_CONTEXT_REQUIRED:"SECURE CONTEXT REQUIRED — HTTPSで開いてください",AUDIO_INITIALIZATION_FAILED:"AUDIO INITIALIZATION FAILED",NOT_STARTED:"NOT STARTED",MICROPHONE_OFF:"MICROPHONE OFF",START_AGAIN:"START ANALYSIS"},
en:{REQUESTING:"Requesting microphone permission…",READY:"MICROPHONE READY",LOW:"LOW INPUT",CLIP:"CLIP — Move the device slightly away",MICROPHONE_BLOCKED:"MICROPHONE BLOCKED — Allow microphone access",MICROPHONE_NOT_FOUND:"MICROPHONE NOT FOUND",MICROPHONE_UNAVAILABLE:"MICROPHONE UNAVAILABLE",SECURE_CONTEXT_REQUIRED:"SECURE CONTEXT REQUIRED — Open over HTTPS",AUDIO_INITIALIZATION_FAILED:"AUDIO INITIALIZATION FAILED",NOT_STARTED:"NOT STARTED",MICROPHONE_OFF:"MICROPHONE OFF",START_AGAIN:"START ANALYSIS"}};
export function getLanguage(){return language}export function msg(k){return messages[language]?.[k]??k}
export function setLanguage(lang){language=lang;document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const v=strings[lang]?.[el.dataset.i18n];if(v!==undefined)el.textContent=v});document.querySelectorAll("[data-ja-only]").forEach(el=>el.hidden=lang!=="ja");document.getElementById("langJa")?.classList.toggle("is-active",lang==="ja");document.getElementById("langEn")?.classList.toggle("is-active",lang==="en");}
