'use strict';

registerLocale('es', {
  meta: { name: 'español' },
  site: {
    documentTitle: 'Instituto de Tecnologías Web No Productivas Impulsadas por IA', eyebrow: 'AI-DRIVEN NON-PRODUCTIVE WEB TECHNOLOGY LAB.', officialLabel: 'NOMBRE OFICIAL DEL INSTITUTO', officialName: 'Instituto de Tecnologías Web No Productivas Impulsadas por IA', tagline: 'Ideas gloriosamente absurdas, con una implementación de nivel de producción.', brandAlias: 'Muda Engineering Lab', languageLabel: 'Idioma', bgmStart: '▶ BGM START', bgmStop: '■ BGM STOP',
    badges: ['🧪 10 PROYECTOS DE INVESTIGACIÓN', '🎮 IMPOSIBLE GANAR SIN JUGAR', '🔊 ACORDES A MÁXIMA POTENCIA', '🎉 FANFARRIA AL COMPLETARLO TODO', '📦 CSS Y JS SEPARADOS POR JUEGO'],
    aboutTitle: 'Acerca de este laboratorio',
    about: ['Muda Engineering Lab es un sitio de parodia inspirado en prácticas laborales ineficientes que podían verse en algunas oficinas japonesas entre las décadas de 1980 y 2000.', 'Documentos en papel, faxes, sellos hanko, reuniones largas y procesos de aprobación complejos formaban parte de la vida cotidiana de muchas oficinas de aquella época.', 'Este sitio exagera deliberadamente esas prácticas y las recrea como juegos con tecnología web moderna, dedicando demasiado esfuerzo de ingeniería a trabajos maravillosamente inútiles.', 'Por supuesto, no todas las empresas japonesas trabajaban así. Esto no es un documento histórico, sino una sátira ficticia que recuerda con humor antiguas costumbres laborales.', 'No es necesario conocer la cultura empresarial japonesa. Antes de cada juego se ofrece una breve explicación de la costumbre laboral que lo inspiró.'],
    back: '← LISTA DE INVESTIGACIONES', controlsPrefix: 'CONTROLES: ', researchNo: 'RESEARCH No.{number}'
  },
  common: { cultureNote: '🧪 REGISTRO DE INVESTIGACIÓN CULTURAL No.{number}', parodyHeading: 'LO QUE PARODIA ESTE JUEGO', beginResearch: 'INICIAR INVESTIGACIÓN', researchComplete: 'RESEARCH COMPLETE', researchCompleteJa: 'INVESTIGACIÓN COMPLETADA', researchSuccess: 'INVESTIGACIÓN EXITOSA', researchFailed: 'RESEARCH FAILED', researchFailedJa: 'INVESTIGACIÓN FALLIDA', promptLabel: 'PETICIÓN INICIAL A LA IA', disclaimer: 'Este programa se creó mediante conversaciones con una IA. No utiliza ninguna API de IA externa mientras se ejecuta.', retry: 'REPETIR LA INVESTIGACIÓN', retryFail: 'REINTENTAR' },
  game01: {
    title: 'PRODUCCIÓN — NO PULSAR.exe', description: 'Ignora las 8 advertencias y completa un rollback de emergencia.', controls: 'CLIC / TOQUE',
    culture: { heading: 'LA CULTURA INFORMÁTICA DE LA ÉPOCA', background: ['Entre las décadas de 1980 y 2000, los sistemas informáticos empresariales estaban menos automatizados que hoy. Los cambios en producción podían ser arriesgados y la recuperación dependía a menudo de quienes conocían el sistema.', 'Cambiar producción un viernes por la tarde, cuando las personas responsables ya se habían marchado o estaban a punto de hacerlo, se convirtió en una pesadilla clásica para los profesionales de TI.'], parody: ['Advertencias, hora tardía, responsables ausentes y una solicitud sin aprobar: este juego exagera al profesional que ignora todas las señales de peligro y se lanza a producción.', 'Aunque el despliegue termine bien, todavía no conviene celebrarlo.'], punchline: 'La verdadera investigación empieza después.' },
    playing: { doNotPress: 'NO PULSAR', warnings: ['DESPLEGAR EN PRODUCCIÓN', '¿SEGURO?', 'HOY ES VIERNES', 'SON LAS 17:48', 'EL RESPONSABLE YA SE FUE', 'EL EQUIPO DE MONITORIZACIÓN TAMBIÉN SE FUE', 'LA SOLICITUD DE CAMBIO NO ESTÁ APROBADA', 'DESPLEGAR DE TODOS MODOS'], warningHeadings: ['NO PULSAR', 'DÉJALO', '¿EN SERIO?', 'ES VIERNES', 'VETE A CASA', 'SIN RESPONSABLE', 'SIN APROBAR'], toldNotTo: '※ Se indicó claramente que no había que pulsarlo.', warningToast: 'ADVERTENCIA {count}/8', passed: 'CONFIRMACIÓN {count}/8 SUPERADA', deploy: 'DEPLOY!!!', deploySuccess: 'DEPLOY SUCCESS', thought: '…¿ESO CREÍAS?', monitoring: 'ALERTA DE MONITORIZACIÓN 9999+', emergencyRollback: 'ROLLBACK DE EMERGENCIA {count}/6', rollback: 'ROLLBACK {count}/6', rollbackHelp: 'PULSA 6 VECES PARA VOLVER ATRÁS' },
    clear: 'Producción restaurada. Causa: «Lo hicimos sin pensarlo».', prompt: 'Crea un botón de despliegue en producción que resulte más tentador cuanto más se prohíba pulsarlo. Convierte también el rollback final en parte del juego.'
  },
  game02: {
    title: 'DEFENSA DE SALIDA A TIEMPO', description: 'Cambia entre 3 carriles, esquiva 12 obstáculos y sal de la oficina.', controls: '↑ ↓ / TOQUE',
    culture: { heading: 'LA CULTURA EMPRESARIAL DE LA ÉPOCA', background: ['Entre las décadas de 1980 y 2000, las jornadas largas eran frecuentes en muchos lugares de trabajo japoneses. Incluso al terminar el horario oficial, podía resultar incómodo marcharse mientras responsables y compañeros seguían trabajando.', 'Justo al disponerse a salir, un responsable podía preguntar «¿Tienes un minuto?» o decir «Solo cinco minutos», dando comienzo a una nueva tarea o reunión.', 'Desde la década de 1990, el correo electrónico y la mensajería instantánea añadieron nuevas formas de que el trabajo siguiera llegando hasta el último momento.'], parody: ['Responsables, correos urgentes, solicitudes de revisión y notificaciones se convierten en obstáculos para impedir la salida a tiempo.', 'Esquiva 12 y escapa de la oficina.'], punchline: 'Salir a tiempo es el objetivo. Probablemente.' },
    playing: { hud: 'ESQUIVADOS {dodges} / 12　HP {hp}', instruction: '↑ ↓ O TOCA EL CARRIL SUPERIOR / INFERIOR', obstacles: ['JEFE: «¿TIENES UN MINUTO?»', '99+ MENSAJES', 'CORREO URGENTE', 'SOLO 5 MINUTOS', '¿VIENES AL ENCUENTRO DEL EQUIPO?', '¿PUEDES REVISAR ESTO?'], dodge: 'DODGE {count}/12' },
    clear: '¡SALIDA A TIEMPO CONSEGUIDA! …Los mensajes siguen llegando.', failure: 'El jefe te ha interceptado. Empieza el «solo una cosa rápida…».', prompt: 'A la hora de salir, esquiva «¿Tienes un minuto?» en tres carriles. El juego se supera con suficientes esquivas y no debe poder completarse sin jugar.'
  },
  game03: {
    title: 'RINGI HANKO IMPACT', description: 'Estampa 20 casillas de aprobación iluminadas en el orden correcto.', controls: 'ARRASTRAR / CLIC',
    culture: { heading: 'EL SISTEMA JAPONÉS DE APROBACIÓN RINGI Y HANKO', background: ['Ringi es un sistema japonés en el que una propuesta o solicitud circula entre las partes implicadas para recibir aprobación. Hanko es el sello usado para dejar constancia de esa aprobación.'], parody: ['El juego exagera la aprobación en múltiples niveles exigiendo 20 sellos para comprar un cable USB de 980 yenes (¥980).', 'Estampa el hanko en cada casilla amarilla y completa las 20 aprobaciones.'], punchline: 'HANKO COMBO convierte una aprobación rutinaria en un ataque especial.' },
    playing: { documentTitle: 'SOLICITUD RINGI DE COMPRA', request: 'SOLICITUD: CABLE USB — ¥980', approval: 'APROBACIONES {count} / 20', stampLabel: 'Sello de aprobación hanko', stamp: '承', hint: 'Arrastra el hanko hasta la casilla iluminada o haz clic en la casilla objetivo.', names: ['SUPERVISOR', 'JEFE DE SECCIÓN', 'JEFE DE DEPARTAMENTO', 'DIRECTOR DE DIVISIÓN', 'FINANZAS', 'LEGAL', 'TI CORPORATIVA', 'AUDITORÍA', 'ASUNTOS GENERALES', 'COMPRAS', 'SEGURIDAD', 'PMO', 'CALIDAD', 'UNIDAD DE NEGOCIO', 'ADMINISTRACIÓN', 'RR. HH.', 'DIRECCIÓN', 'DEPARTAMENTO MISTERIOSO', 'DEPARTAMENTO RELACIONADO', 'APROBACIÓN FINAL'], wrongOrder: 'ORDEN DE APROBACIÓN INCORRECTO', combo: 'HANKO COMBO ×{count}' },
    clear: 'APROBADO: ya puedes comprar el cable USB de ¥980.', prompt: 'Crea un juego en el que solo haya que estampar, por orden, una enorme solicitud ringi llena de hanko, con efectos dignos de un ataque especial.'
  },
  game04: {
    title: 'RESPUESTA INFINITA A INCIDENTES', description: 'Recupera 25 incidentes antes de que se agote el SLA.', controls: 'CLIC / TOQUE',
    culture: { heading: 'LOS INCIDENTES DE TI EMPRESARIAL', background: ['Las operaciones de TI empresarial están llenas de situaciones conocidas: incidentes, SLA, causas desconocidas, fallos imposibles de reproducir y sistemas que solo entiende una persona.'], parody: ['El juego los exagera como un desafío de clics rápidos donde los incidentes sin resolver reducen cada vez más el SLA. Recupera 25.'], punchline: 'Los incidentes no esperan a que aparezca la causa raíz.' },
    playing: { hud: 'RECUPERADOS {done} / 25　SLA {sla} %', open: 'ABIERTOS {count} / 7', help: 'Haz clic en los incidentes rojos para recuperarlos. Tras 5 segundos de gracia, los incidentes pendientes derriten el SLA.', grace: 'RESPUESTA INICIAL: {seconds} s　¡PULSA LOS INCIDENTES!', incidents: ['ERROR DE CONEXIÓN A LA DB', 'SEGURO QUE ES EL DNS', 'CERTIFICADO VENCIDO', 'AYER FUNCIONABA', 'EN MI EQUIPO FUNCIONA', 'NO SE PUEDE REPRODUCIR', 'CAUSA: DESCONOCIDA'], recover: 'RECOVER {count}/25' },
    clear: 'Causa identificada: funcionaba según lo especificado.', failure: 'SLA 0 %. Ha comenzado la redacción del informe del incidente.', prompt: 'Crea un juego tipo golpear al topo donde reparar incidentes genera otros nuevos y los elementos pendientes reducen el SLA.'
  },
  game05: {
    title: 'ESQUIVA LOS CAMBIOS DE REQUISITOS', description: 'Esquiva 20 cambios antes de recibir 3 impactos y publica la versión.', controls: '← → / TOQUE',
    culture: { heading: 'CAMBIOS DURANTE EL DESARROLLO', background: ['Durante el desarrollo pueden seguir llegando nuevas peticiones, cambios de requisitos y ampliaciones del alcance.'], parody: ['Las peticiones repentinas se convierten en objetos que caen. Muévete a izquierda y derecha y esquiva 20.'], punchline: 'Los requisitos crecen más rápido justo antes de la publicación.' },
    playing: { hud: 'ESQUIVADOS {dodges} / 20　HP {hp}', instruction: '← → O TOCA EL LADO IZQUIERDO / DERECHO', changes: ['CAMBIAR EL TEXTO', 'MOVER EL BOTÓN', 'AÑADIR SOPORTE MÓVIL', 'PENSAR EN EL MERCADO GLOBAL', '¿PODEMOS AÑADIR IA?', 'TAMBIÉN QUEREMOS CAMBIAR LA DB', 'REVISARLO TODO DESDE CERO'], avoid: 'AVOID {count}/20' },
    clear: '¡PUBLICACIÓN CONSEGUIDA! …Ya ha llegado el siguiente cambio.', failure: 'Sepultado bajo los cambios. Comienza el SPRINT 2.', prompt: 'Haz que los cambios caigan por toda la pantalla mientras el jugador se mueve a izquierda y derecha. Cada esquiva correcta aumenta el progreso.'
  },
  game06: {
    title: 'CRAFT DE PAPEL CUADRICULADO EN EXCEL', description: 'Colorea solo las celdas del plano y completa el castillo Excel.', controls: 'CLIC / TOQUE',
    culture: { heading: 'LA COSTUMBRE JAPONESA DEL PAPEL CUADRICULADO EN EXCEL', background: ['En algunas oficinas japonesas, Excel se utiliza como papel cuadriculado: se ajustan cuidadosamente el ancho y alto de las celdas para crear formularios, planos y diseños de documentos.'], parody: ['Colorea las celdas según el plano y completa las 36 requeridas. Cinco errores devuelven el trabajo a revisión.'], punchline: 'Construye el castillo Excel sin combinar celdas.' },
    playing: { hud: 'CORRECTAS {ok} / {total}　ERRORES {wrong} / 5', heading: 'CRAFT EXCEL: PLANO CUADRICULADO', hint: 'Pon en verde únicamente las celdas marcadas. Cinco errores activan una revisión.', cellLabel: 'Celda {x},{y}', cell: 'CELL {count}/{total}' },
    clear: 'Castillo Excel terminado. Ahora está prohibido combinar celdas.', failure: 'Desviación del plano. Devuelto al experto en Excel para revisión.', prompt: 'Crea un reto absurdamente parecido a un juego donde se coloreen celdas según un plano de papel cuadriculado en Excel para construir un castillo.'
  },
  game07: {
    title: 'GENERADOR DE PROGRESO AL 100 %', description: 'Lleva el progreso al 100 % pese a las repetidas solicitudes de cambio.', controls: 'CLIC RÁPIDO / TOQUE',
    culture: { heading: 'LA CULTURA DEL PORCENTAJE DE PROGRESO', background: ['A veces el porcentaje de progreso sigue aumentando aunque resulte difícil encontrar un resultado real del trabajo.'], parody: ['Este dispositivo genera progreso mediante clics repetidos. Alcanza el 100 % pese a los cambios solicitados aproximadamente cada cuatro segundos.'], punchline: 'Un progreso del 100 % no garantiza que exista un resultado real.' },
    playing: { reviewIn: 'CAMBIOS EN {seconds} s', generate: 'GENERAR PROGRESO', combo: 'COMBO ×{count}', hint: 'Pulsa rápidamente. Se solicitan cambios cada 4 segundos.', review: '¡CAMBIOS SOLICITADOS! -{loss} %' },
    clear: 'PROGRESO: 100 %. No se encontró ningún resultado real del trabajo.', prompt: 'Crea un botón que aumente el progreso al pulsarlo, pero lo reduzca periódicamente cuando se soliciten cambios.'
  },
  game08: {
    title: 'TEMPLO KUYŌ DE BUGS', description: 'Despide 15 bugs. Si escapan 5, la investigación fracasa.', controls: 'CLIC / TOQUE',
    culture: { heading: 'LA TRADICIÓN JAPONESA DEL KUYŌ', background: ['En Japón, kuyō es la tradición de agradecer, honrar y despedir con respeto a los objetos que han terminado su vida útil.', 'Existen ceremonias para agujas usadas y muñecas, a las que se expresa gratitud antes de despedirlas.', 'En el desarrollo de software, un «bug» es un defecto del programa.'], parody: ['En Muda Engineering Lab hemos decidido no corregir los bugs, sino ofrecerles un kuyō al son del mokugyo, instrumento de percusión budista de madera.', 'Haz clic en los bugs que huyen y despide 15.', 'Los bugs abandonados escapan a producción. Si escapan cinco, la investigación fracasa.'], punchline: 'Que todos los bugs descansen en paz.' },
    playing: { hud: 'DESPEDIDOS {done} / 15　ESCAPADOS {escaped} / 5', output: 'POTENCIA DEL MOKUGYO 300 %', production: '🚨 PRODUCCIÓN', instruction: 'Haz clic en los 🐛 bugs y despídelos en paz.', hint: '¡Los bugs rojos escapan a producción!', escaping: '🚨 ESCAPANDO A PRODUCCIÓN', memorialized: 'DESCANSA EN PAZ {done}/15', prevented: '¡ESCAPE IMPEDIDO! DESCANSA EN PAZ {done}/15', escapeStart: '🚨 ¡ESCAPANDO A PRODUCCIÓN!', escaped: '¡ESCAPE A PRODUCCIÓN! {escaped}/5' },
    clear: 'Todos los bugs descansan en paz. Se ha detectado uno nuevo.', failure: 'Cinco bugs escaparon a producción. La respuesta a incidentes tiene prioridad sobre el kuyō.', prompt: 'Ofrece un kuyō a bugs de software con un mokugyo, instrumento de percusión budista de madera. Los bugs huyen y cada escape acerca la investigación al fracaso.'
  },
  game09: {
    title: 'SIMULADOR DE ESCAPE DE REUNIONES', description: 'Sal durante la ventana «¿Algo más?» un total de 3 veces.', controls: 'CLIC DE PRECISIÓN / TOQUE',
    culture: { heading: 'LA CULTURA EMPRESARIAL DE LA ÉPOCA', background: ['Entre las décadas de 1980 y 2000, las reuniones eran una forma frecuente de compartir información y coordinar decisiones entre muchos participantes en empresas japonesas.', 'Al terminar una reunión larga, quien la presidía podía preguntar: «¿Algo más?»', 'Si nadie respondía, la reunión podía terminar por fin.', 'Pero alguien podía añadir «Solo un punto más…», «Sobre eso…» o «Una actualización rápida…», y la reunión continuaba.'], parody: ['El momento en que aparece «¿Algo más?» es la oportunidad de escapar.', 'Pulsa SALIR en el momento exacto y acierta tres veces.'], punchline: 'Una reunión es más peligrosa justo cuando parece terminada.' },
    playing: { hud: 'ESCAPES {count} / 3', inProgress: 'REUNIÓN EN CURSO...', roles: ['JEFE DE DEPARTAMENTO', 'PM', 'DESARROLLADOR', 'TÚ'], leave: 'SALIR', instruction: 'Pulsa solo cuando aparezca «¿Algo más?».', lines: ['SIGUIENTE PUNTO...', 'SOLO UN PUNTO MÁS...', 'SOBRE ESO...', 'UNA ACTUALIZACIÓN RÁPIDA...'], chance: '¿ALGO MÁS?', toast: 'ESCAPE CHANCE {count}/3', notOver: 'AÚN NO HA TERMINADO' },
    clear: '¡ESCAPE CONSEGUIDO! «Entonces, terminamos» existía de verdad.', prompt: 'Crea un juego de reuniones donde solo se pueda salir durante la breve ventana «¿Algo más?» y haya que acertar tres veces.'
  },
  game10: {
    title: 'SANTUARIO DEL SERVIDOR DE PRODUCCIÓN', description: 'Toca la campana en la zona luminosa 7 veces seguidas.', controls: 'CLIC DE PRECISIÓN / TOQUE',
    culture: { heading: 'LA TRADICIÓN JAPONESA DE LOS SANTUARIOS SINTOÍSTAS', background: ['En Japón se visitan santuarios sintoístas para pedir éxito, seguridad, salud y buena fortuna.', 'En algunos santuarios, los visitantes tocan una campana antes de rezar. Los papeles de la fortuna omikuji pueden dar resultados como Daikichi, una gran fortuna.', 'Para un profesional de TI, desplegar en producción puede seguir siendo estresante incluso después de completar pruebas, revisiones y preparativos.'], parody: ['Las pruebas han terminado. Las revisiones también.', 'Solo queda rezar para que producción sobreviva.', 'Toca la campana dentro de la zona de éxito siete veces seguidas.'], punchline: 'El último 1 % de fiabilidad queda ahora en manos de la plegaria.' },
    playing: { hud: 'COMBO DE PLEGARIA {count} / 7', waiting: 'ESTADO: EN ESPERA', lucky: 'ESTADO: BUEN AUGURIO', luckyZone: 'TOCA LA CAMPANA EN LA ZONA LUMINOSA', instruction: '¡TOCA CUANDO BRILLE!', now: '¡AHORA!', ring: '🔔 TOCAR LA CAMPANA', combo: 'COMBO DE PLEGARIA ×{count}', premature: '¡PLEGARIA DEMASIADO PRONTO!' },
    clearTitle: 'DAIKICHI — GRAN FORTUNA', clear: 'La probabilidad de éxito del despliegue no ha cambiado.', clearPunchline: 'Pero ahora te sientes mucho más tranquilo.', prompt: 'Antes de desplegar en producción, limítate a rezar en un santuario. Convierte el acto de tocar la campana en la zona luminosa en un juego de precisión.'
  }
});
